#This workflow will build and deploy our Lambda function microservice
name: Amazon Lambda Function

env:
  AWS_REGION: us-east-1
  AWS_LAMBDA_FUNCTION_NAME: emailVerify
  ENVIRONMENT: prod

on:
  push:
    branches: [master]
jobs:
  lambda_deploy:
    runs-on: ubuntu-latest
    name: Deploy Lambda Function
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create the .env file
        run: |
          touch .env
          echo TrackUserEmailDynamoDBTable=${{ secrets.DYDBTABLE}} >> .env
          echo TrackUserEmailDynamoDBRegion=${{ env.AWS_REGION}} >> .env
          echo DomainEnvironment=${{ env.ENVIRONMENT}} >> .env

      - name: Create the artifact
          zip -r serverless.zip ./
          chmod +x serverless.zip

      - name: Deploy the Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ env.AWS_LAMBDA_FUNCTION_NAME }} --zip-file fileb://serverless.zip

      - name: Cleanup artifacts
        run: |
          rm -rf serverless.zip
